const getWord = () => {
    const kataMakanan = [
        "NasiGoreng",
        "Pizza",
        "Sushi",
        "Burger",
        "Rendang",
        "Pasta",
        "Sate",
        "DimSum",
        "Soto",
        "Salad",
        "Taco",
        "NasiKuning",
        "Pancake",
        "Kebab",
        "Bakso",
        "NasiUduk",
        "Kimbap",
        "Steak",
        "MieAyam",
        "Cireng",
        "EsKrim",
        "RotiBakar",
        "Gado-Gado",
        "Pempek",
        "MieGoreng",
        "Martabak",
        "NasiPadang",
        "Donat",
        "SopBuntut",
        "KwetiauGoreng",
        "AyamGoreng",
        "IkanBakar",
        "BuburAyam",
        "Risotto",
        "Lobster",
        "Sashimi",
        "Puding",
        "Sambal",
        "Ketoprak",
        "LontongSayur",
        "Pecel",
        "BuburSumsum",
        "CotoMakassar",
        "EsDoger",
        "Rawon",
        "Murtabak",
        "CumiGoreng",
        "Ketupat",
        "PisangGoreng",
        "Rujak",
        "TahuTek",
      ];
      return kataMakanan[Math.floor(Math.random()*kataMakanan.length)]
      
}
 
module.exports = getWord