const getWord = () => {
    const kataKata = [
      "nasigoreng",
      "ikanhiu",
      "sushi",
      "keong",
      "rendang",
      "unta",
      "sate",
      "monyet",
      "soto",
      "orangutan",
      "taco",
      "siput",
      "pancake",
      "serigala",
      "bakso",
      "ikankoi",
      "kimbap",
      "steak",
      "sapi",
      "cireng",
      "eskrim",
      "kambing",
      "gado-gado",
      "pempek",
      "bebek",
      "martabak",
      "nasipadang",
      "donat",
      "soang",
      "kwetiaugoreng",
      "ayamgoreng",
      "ayam",
      "buburayam",
      "kuda",
      "lobster",
      "sashimi",
      "barakuda",
      "sambal",
      "ketoprak",
      "lontongsayur",
      "pecel",
      "gurita",
      "cotomakassar",
      "esdoger",
      "cumi",
      "martabak",
      "cumigoreng",
      "ketupat",
      "pisanggoreng",
      "rujak",
      "tahutek",
      ];
      return kataKata[Math.floor(Math.random()*kataKata.length)]
      
}
 
module.exports = getWord