const getWord = () => {
    const kataMakanan = [
      "nasigoreng",
      "pizza",
      "sushi",
      "burger",
      "rendang",
      "pasta",
      "sate",
      "dimsum",
      "soto",
      "salad",
      "taco",
      "nasikuning",
      "pancake",
      "kebab",
      "bakso",
      "nasiuduk",
      "kimbap",
      "steak",
      "mieayam",
      "cireng",
      "eskrim",
      "rotibakar",
      "gado-gado",
      "pempek",
      "miegoreng",
      "martabak",
      "nasipadang",
      "donat",
      "sopbuntut",
      "kwetiaugoreng",
      "ayamgoreng",
      "ikanbakar",
      "buburayam",
      "risotto",
      "lobster",
      "sashimi",
      "puding",
      "sambal",
      "ketoprak",
      "lontongsayur",
      "pecel",
      "bubursumsum",
      "cotomakassar",
      "esdoger",
      "rawon",
      "murtabak",
      "cumigoreng",
      "ketupat",
      "pisanggoreng",
      "rujak",
      "tahutek",
      ];
      return kataMakanan[Math.floor(Math.random()*kataMakanan.length)]
      
}
 
module.exports = getWord